### ISSUE TITLE
Where can I find the checksum for each release?

### ISSUE THREAD

**Issue by mhenrixon** [postmodern/chruby#325]
Can't find it anywhere and need it.

**Comment by aprescott** [comment]
Unless I don't understand your question, this doesn't seem like a chruby thing, since it only takes care of switching installed Rubies. [ruby-install](https://github.com/postmodern/ruby-install) installs Rubies and it uses checksums from [ruby-versions](https://github.com/postmodern/ruby-versions). Try looking at [ruby-versions](https://github.com/postmodern/ruby-versions)?

**Comment by aprescott** [comment]
(You may be using an entirely different piece of software for actually installing Rubies, though.)

**Comment by mhenrixon** [comment]
Nah it was for chruby because some arc checksum validation. Ended up choosing another chef cookbook to install stuff.
