### ISSUE TITLE
Cannot install latest ruby through chruby on Mac M2 Apple Chip

### ISSUE THREAD

**Issue by Waterkin** [postmodern/chruby#483]
## Description

Cannot install latest ruby through chruby on Mac M2 Apple Chip

## Steps To Reproduce

Steps to reproduce the bug:
1. `brew install chruby ruby-install xz`
2. `ruby-install ruby`

## Actual Behavior
```
>>> Updating ruby versions ...
!!! Failed to download https://raw.githubusercontent.com/postmodern/ruby-versions/master/ruby/versions.txt to /Users/ppwang/.cache/ruby-install/ruby/versions.txt!
!!! Failed to download ruby versions!
```

## Environment

    $ chruby --version
    chruby: 0.3.9

**Comment by postmodern** [comment]
This does not appear to be a chruby issue, but could be a network or SSL related issue, or maybe related to [ruby-install](https://github.com/postmodern/ruby-install). Have you tried to manually download the file with `curl` or `wge` to test whether it is a networking or SSL related issue?

If your system has `curl` installed:

```shell
$ curl -f -L -C - -o /Users/ppwang/.cache/ruby-install/ruby/versions.txt https://raw.githubusercontent.com/postmodern/ruby-versions/master/ruby/versions.txt
```

If your system has `wget` installed:

```shell
$ wget -c -O /Users/ppwang/.cache/ruby-install/ruby/versions.txt https://raw.githubusercontent.com/postmodern/ruby-versions/master/ruby/versions.txt
```

If you get an error message from the `curl`/`wget` command, then the problem is related to the network, SSL, or possibly disk space. If the command works, and the problem persists with `ruby-install`, then please report it to [ruby-install](https://github.com/postmodern/ruby-install/issues).
